"""Correccion relaciones

Revision ID: b4bc21bfbbc2
Revises: 
Create Date: 2025-03-30 00:49:35.530492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4bc21bfbbc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientes')
    with op.batch_alter_table('pizzas', schema=None) as batch_op:
        batch_op.drop_constraint('pizzas_categoria_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categorias_pizza', ['categoria_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pizzas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pizzas_categoria_id_fkey', 'categorias_pizza', ['categoria_id'], ['id'], ondelete='SET NULL')

    op.create_table('clientes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('direccion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='clientes_pkey'),
    sa.UniqueConstraint('email', name='clientes_email_key')
    )
    # ### end Alembic commands ###
